import os
import sys
import numpy as np
import onnxruntime as ort

from utils import DataPoint, ScorerStepByStep

# Adjust path to import utils from parent directory
CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.append(f"{CURRENT_DIR}/..")


class PredictionModel:
    """
    Baseline Solution (Vanilla GRU).

    This solution uses a simple GRU model trained on 32 features
    to predict t0 and t1.

    Note: This code was generated by an LLM as a baseline demonstration.
    """

    def __init__(self, model_path=""):
        self.current_seq_ix = None
        self.hidden_state = None

        # Determine paths
        onnx_path = "trained_model.onnx"

        # Initialize ONNX Runtime Session
        sess_options = ort.SessionOptions()
        sess_options.intra_op_num_threads = 1
        sess_options.inter_op_num_threads = 1
        sess_options.graph_optimization_level = (
            ort.GraphOptimizationLevel.ORT_ENABLE_ALL
        )

        self.ort_session = None

        try:
            # Load ONNX Model
            self.ort_session = ort.InferenceSession(
                onnx_path, sess_options, providers=["CPUExecutionProvider"]
            )
            self.input_name = self.ort_session.get_inputs()[0].name
            self.h_name = self.ort_session.get_inputs()[1].name
            self.c_name = self.ort_session.get_inputs()[2].name

            self.output_name = self.ort_session.get_outputs()[0].name
            self.num_layers = 4
            self.hidden_size = 128
            self.reset_states()
            print(f"Loaded ONNX model from {onnx_path}")

        except Exception as e:
            print(f"Error loading model resources: {e}")
            self.ort_session = None

    def reset_states(self):
        self.h_state = np.zeros(
            (self.num_layers, 1, self.hidden_size), dtype=np.float32
        )
        self.c_state = np.zeros(
            (self.num_layers, 1, self.hidden_size), dtype=np.float32
        )

    def predict(self, data_point: DataPoint) -> np.ndarray:

        # Reset state on new sequence
        if self.current_seq_ix != data_point.seq_ix:
            self.current_seq_ix = data_point.seq_ix
            self.reset_states()

        # Run inference
        ort_inputs = {
            self.input_name: data_point.state.reshape(1, 1, -1).astype("float32"),
            self.h_name: self.h_state,
            self.c_name: self.c_state,
        }

        outputs = self.ort_session.run(None, ort_inputs)
        prediction, self.h_state, self.c_state = outputs

        if not data_point.need_prediction:
            return None
        else:
            return prediction[0][0]


if __name__ == "__main__":
    # Local testing
    test_file = "./datasets/valid.parquet"

    if os.path.exists(test_file):
        model = PredictionModel()
        scorer = ScorerStepByStep(test_file)

        print("Testing lstm...")
        results = scorer.score(model)

        print("\nResults:")
        print(f"Mean Weighted Pearson correlation: {results['weighted_pearson']:.6f}")
        for i, target in enumerate(scorer.targets):
            print(f"  {target}: {results[target]:.6f}")
    else:
        print("Valid parquet not found for testing.")
